server:
    port: 8083

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:10001/eureka/

spring:
    application:
        name: ${project.name}
    datasource:
        url: jdbc:oracle:thin:@10.64.26.9:1523:CAVDST
        username: VDS
        password: VDS111111VDS
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
mybatis:
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    typeAliasesPackage: com.foreveross.vds.service.**.vo
    configLocation: classpath:/META-INF/mybatis/mybatis-config.xml
 
logging:
    pattern:
        console: "%d - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} %5p"
    level.com.foreveross.vs: info
    path: logs
    file: ${project.name}.log
