package com.foreveross.vds.service.fms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.foreveross.vds.vo.fms.FmsCarCategory;

@Mapper
public interface FmsCarCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMS.FMS_CAR_CATEGORY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long carCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMS.FMS_CAR_CATEGORY
     *
     * @mbg.generated
     */
    int insert(FmsCarCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMS.FMS_CAR_CATEGORY
     *
     * @mbg.generated
     */
    FmsCarCategory selectByPrimaryKey(Long carCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMS.FMS_CAR_CATEGORY
     *
     * @mbg.generated
     */
    List<FmsCarCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMS.FMS_CAR_CATEGORY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FmsCarCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FMS.FMS_CAR_CATEGORY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FmsCarCategory record);

    /**
     * 过滤查询
     * @param fmsCarCategory
     * @return
     */
    List<FmsCarCategory> selectByWhere(FmsCarCategory fmsCarCategory);
    
    List<FmsCarCategory> selectByWhereNotLike(FmsCarCategory fmsCarCategory);

    /**
     *
     * @param carCategoryCode
     * @param carCategoryId
     * @return
     */
    int countExistsCode(@Param("carCategoryCode") String carCategoryCode, @Param("carCategoryId") Long carCategoryId);
}