package com.foreveross.vds.service.fms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.foreveross.vds.dto.fms.FmsCarCategoryReleationRequest;
import com.foreveross.vds.vo.fms.FmsCarCategoryReleation;
import com.foreveross.vds.vo.inv.InvCarSeries;
import com.github.pagehelper.Page;

@Mapper
public interface FmsCarCategoryReleationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMS.TMS_START_POINT_ORG_REALATION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long carCategoryReleationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMS.TMS_START_POINT_ORG_REALATION
     *
     * @mbg.generated
     */
    int insert(FmsCarCategoryReleation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMS.TMS_START_POINT_ORG_REALATION
     *
     * @mbg.generated
     */
    FmsCarCategoryReleation selectByPrimaryKey(Long carCategoryReleationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMS.TMS_START_POINT_ORG_REALATION
     *
     * @mbg.generated
     */
    List<FmsCarCategoryReleation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMS.TMS_START_POINT_ORG_REALATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FmsCarCategoryReleation record);

    /**
     *
     * @param fmsCarCategoryReleationRequest
     * @return
     */
    List<FmsCarCategoryReleation> selectRelationByWhereClause(FmsCarCategoryReleationRequest fmsCarCategoryReleationRequest);

    List<FmsCarCategoryReleation> selectRelationByWhereClauseNotLike(FmsCarCategoryReleationRequest fmsCarCategoryReleationRequest);
    
    /**
     * 查询左侧
     * @return
     */
    List<InvCarSeries> leftQuery(@Param("carSeriesCode") String carSeriesCode, @Param("carCategoryId") Long carCategoryId);

    /**
     * 查询右侧
     * @return
     */
    List<InvCarSeries> rightQuery(Long carCategoryId);

    /**
     * 根据车系代码查询车系数据
     * @param invCarSeriesParam
     * @return
     */
    List<InvCarSeries> selectCarSeriesBy(InvCarSeries invCarSeriesParam);

    /**
     * 根据车型代码查询车系数据
     * @param invCarSeriesParam
     * @return
     */
	List<InvCarSeries> selectCarSeriesByVehicleCode(InvCarSeries invCarSeries);

	Page<FmsCarCategoryReleation> selectRelationByWhereClauseNotSeries(
			FmsCarCategoryReleationRequest fmsCarCategoryReleationRequest);

	InvCarSeries selectCarSeriesById(InvCarSeries invCarSeries);

	
}